### ISSUE TITLE
Utilizado em Produção?

### ISSUE THREAD

**Issue by bernardoVale** [endersonmaia/totvs-dbaccess-docker#1]
Olá @endersonmaia , parabéns pela iniciativa, há muito venho pensando em fazer um teste de Docker com os componentes do Protheus.

Você chegou a colocar esse dbaccess em produção desta forma? Apresentou alguma dificuldade? 

Gostaria de auxiliar esse repositório, já tenho uma build docker com o `oracle instantclient`, poderia fazer uma tag exclusiva para `oracle`.

**Comment by endersonmaia** [comment]
Olá @bernardoVale , nada em produção ainda!

Fique a vontade para colaborar.

Uma dificuldade que tenho é configurar o DBAccess de forma não interativa, sem necessitar abrir o `dbmonitor`. Se vc tiver alguma ideia quanto a isto, seria ótimo.

Pq daí passaríamos as senhas via variáveis de ambiente, na inicialização do container.

**Comment by bernardoVale** [comment]
Sim, seria uma boa ideia configurar tudo por env. Eu nunca fiz isso sem abrir o configurador, porque o TOTVS precisa criptografar a senha pra colocar no arquivo dbaccess.ini.

**Comment by endersonmaia** [comment]
Eu mantive contato com um cara da TOTVS, que estava também experimentando o Docker, e ele informou que existia um binário dbconfig, em linha de comando, para fazer a configuração do dbaccess, mas nunca encontrei este binário nos arquivos fornecidos pela TOTVS.

Se vc tiver acesso a alguém de lá, talvez consiga isso aí. :)

Outra coisa legal, seria configurar com o MSSQL Server 2016 para Linux, que deve lançar versão em container em breve.

**Comment by bernardoVale** [comment]
Bacana, se achasse ia resolver muitos problemas pra mim também. Eu vou tentar ver algum contato que possa ajudar nisso.
